### PR TITLE
added hpfeeds logging support.

### PR DESCRIPTION
**Pull request by vorband**
for hpfeeds, the following env variables must be set
HPFEEDS_SERVER
HPFEEDS_IDENT
HPFEEDS_SECRET
HPFEEDS_PORT
SERVERID (e.g. name/identifier)

Please test before merging! :)

### CODE REVIEW

**Comment by t3chn0m4g3** [comment]
Merged the PR locally and I am getting the following error upon `rdpy` start:

```
rdpy    | Traceback (most recent call last):
rdpy    |   File "/usr/bin/rdpy-rdphoneypot.py", line 4, in <module>
rdpy    |     __import__('pkg_resources').run_script('rdpy==1.3.2', 'rdpy-rdphoneypot.py')
rdpy    |   File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 739, in run_script
rdpy    |     self.require(requires)[0].run_script(script_name, ns)
rdpy    |   File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1501, in run_script
rdpy    |     exec(script_code, namespace, namespace)
rdpy    |   File "/usr/lib/python2.7/site-packages/rdpy-1.3.2-py2.7-linux-x86_64.egg/EGG-INFO/scripts/rdpy-rdphoneypot.py", line 27, in <module>
rdpy    |     
rdpy    |   File "build/bdist.linux-x86_64/egg/rdpy/core/hpfeedslog.py", line 20, in <module>
rdpy    | ImportError: No module named hpfeeds
rdpy    | >>> 
rdpy exited with code 0
```

**Comment by vorband** [comment]
pip install hpfeeds. :)

**Review by t3chn0m4g3 — CHANGES_REQUESTED** [review]
`setup.py` needs `hpfeeds` req.

**Comment by t3chn0m4g3** [comment]
Getting this error upon connection request:

```
rdpy    | Unhandled Error
rdpy    | Traceback (most recent call last):
rdpy    |   File "/usr/lib/python2.7/site-packages/twisted/python/log.py", line 86, in callWithContext
rdpy    |     return context.call({ILogContext: newCtx}, func, *args, **kw)
rdpy    |   File "/usr/lib/python2.7/site-packages/twisted/python/context.py", line 122, in callWithContext
rdpy    |     return self.currentContext().callWithContext(ctx, func, *args, **kw)
rdpy    |   File "/usr/lib/python2.7/site-packages/twisted/python/context.py", line 85, in callWithContext
rdpy    |     return func(*args,**kw)
rdpy    |   File "/usr/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
rdpy    |     why = selectable.doRead()
rdpy    | --- <exception caught here> ---
rdpy    |   File "/usr/lib/python2.7/site-packages/twisted/internet/tcp.py", line 1066, in doRead
rdpy    |     protocol = self.factory.buildProtocol(self._buildAddr(addr))
rdpy    |   File "build/bdist.linux-x86_64/egg/rdpy/core/layer.py", line 149, in buildProtocol
rdpy    |     
rdpy    |   File "build/bdist.linux-x86_64/egg/rdpy/protocol/rdp/rdp.py", line 600, in buildRawLayer
rdpy    |     
rdpy    |   File "/usr/lib/python2.7/site-packages/rdpy-1.3.2-py2.7-linux-x86_64.egg/EGG-INFO/scripts/rdpy-rdphoneypot.py", line 127, in buildObserver
rdpy    |     hpfeedslog.info("%s, Connection from %s:%s"%(datetime.datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%S.%fZ'), addr.host, addr.port))
rdpy    |   File "build/bdist.linux-x86_64/egg/rdpy/core/hpfeedslog.py", line 83, in info
rdpy    |     
rdpy    |   File "build/bdist.linux-x86_64/egg/rdpy/core/hpfeedslog.py", line 95, in send_hpfeeds
rdpy    |     
rdpy    | exceptions.NameError: global name 'hpc' is not defined
rdpy    | 

```

Checked if it had to do anything with setting to `read_only:true` or the ENVs, but this is unfortunately not the case.

**Comment by vorband** [comment]
try again and set the variables

**Comment by t3chn0m4g3** [comment]
LGTM

**Comment by vorband** [comment]
do you push the changes upstream ?

**Comment by t3chn0m4g3** [comment]
Yes.

**Pull request merged**
